### ISSUE TITLE
Loadout options can not be unselected.

### ISSUE THREAD

**Issue by DangerRevolution** [Simple-Station/Einstein-Engines#498]
# Description

(at least on deepstation; need to confirm for base EE). Title.

**Comment by DEATHB4DEFEAT** [comment]
I think this is just an issue on DS.

**Comment by DangerRevolution** [comment]
> I think this is just an issue on DS.

https://discord.com/channels/1218698320155906090/1218698321053356060/1257026766443380896

Mnemo has found that once points are in the negative; unselecting becomes locked.

**Comment by WarMechanic** [comment]
it might also have something to do with duplicate slot items, like having two uniforms

which in turn could have something to do with the doll renderer

**Comment by WarMechanic** [comment]
i reproduced it on DS, you cant unselect stuff at 0 points or less

**Comment by WarMechanic** [comment]
also reproduced it on EE, this is in fact an EE issue
ill see if i can investigate it now but its 2am

**Comment by WarMechanic** [comment]
found it
if you go to `C.C/Preferences/UI/HumanoidProfileEditor.xaml.cs`, line 2089

`//preference = preference ? CheckPoints(points, preference) : CheckPoints(-points, preference);`
if you comment out this point checker then it stops blocking changes to loadout, for some reason
aside from that i dont know how to read the code and its almost 3am so im going to bed

if nobody picks up i can work on it tomorrow

**Comment by Mnemotechnician** [comment]
The issue is the conflict between lines 2089 and 2100-2103, CheckPoints(points, preference). The function returns `freePoints + points >= 0` if `preference` is true, and `freePoints + points < 0` otherwise. The caller on the line 2089 invokes `CheckPoints(points, preference)`  if `preference` is true, and `CheckPoints(-points, preference)` otherwise. This simplifies to `freePoints + points >= 0` when turning the preference OFF, and `freePoints - points < 0` when turning ON.
